name = "simplifile"
version = "0.1.1"
description = "Basic file operations that work on all targets"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
licences = ["Apache-2.0"]
repository = { type = "github", user = "bcpeinhardt", repo = "simplifile" }
# links = [{ title = "Website", href = "https://gleam.run" }]

[javascript.deno]
allow_all = true

[dependencies]
gleam_stdlib = "~> 0.29"
gleam_erlang = "~> 0.19"
gleam_javascript = "~> 0.4"

[dev-dependencies]
gleeunit = "~> 0.10"
